blank_issues_enabled: false
contact_links:
  - name: "SPSWeather Discussions"
    url: https://github.com/luigilink/SPSWeather/discussions
    about: "To engage with the community and maintainers of SPSWeather, please visit the discussions group. There, you can share feedback, ask questions, and collaborate with others working on SPSWeather."
